// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBC_bszLojVBZcfcsAg_TpllQzE1LKbuQ',
    appId: '1:254575177319:android:356525fea5470a8ef9aec2',
    messagingSenderId: '254575177319',
    projectId: 'invoicefoxy',
    storageBucket: 'invoicefoxy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnQO7Iuvbjuf8I2qhG8WzRqeVm55P_zog',
    appId: '1:254575177319:ios:276452b50fb10f1df9aec2',
    messagingSenderId: '254575177319',
    projectId: 'invoicefoxy',
    storageBucket: 'invoicefoxy.firebasestorage.app',
    iosBundleId: 'com.nylo.ios',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpM1W6XRHvQ9_k-gwqEWh9efrEk5jUYcE',
    appId: '1:254575177319:web:d9fed059f1fcae70f9aec2',
    messagingSenderId: '254575177319',
    projectId: 'invoicefoxy',
    authDomain: 'invoicefoxy.firebaseapp.com',
    storageBucket: 'invoicefoxy.firebasestorage.app',
  );

}